# -*- coding: utf-8 -*-
"""Hierarchical Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyScyp7Uqo12Ss0br3l7gRpjChZIscZC
"""

# Do the neccesary imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

dataset = pd.DataFrame ({
     'a' : [12, 14, 19, 22, 11, 9, 25, 28, 30, 7, 10, 24, 27, 29, 33, 23, 16, 13, 26, 31],
     'b' : [21, 41, 91, 22, 12, 8, 52, 82, 32, 5, 4, 42, 72, 92, 34, 37, 61, 62, 44, 55 ]
 })

dataset = make_blobs(n_features = 2,
                     centers = 3,
                     cluster_std = 1.6,
                     random_state = 100)

points = dataset[0]

import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering

#create a dendogram
dendorgram = sch.dendrogram(sch.linkage(points, method = 'ward'))

plt.scatter(dataset[0][:, 0], dataset[0][:, 1])

# perform rhe actural clustering
hc = AgglomerativeClustering(n_clusters = 4, affinity = 'euclidean', linkage = 'ward')

y_hc = hc.fit_predict(points)

plt.scatter(points[y_hc == 0,0], points[y_hc == 0,1], s = 100, c = 'cyan')
plt.scatter(points[y_hc == 1,0], points[y_hc == 1,1], s = 100, c = 'orange')
plt.scatter(points[y_hc == 2,0], points[y_hc == 2,1], s = 100, c = 'purple')
plt.scatter(points[y_hc == 3,0], points[y_hc == 3,1], s = 100, c = 'green')